apiVersion: v1
kind: Pod
metadata:
  namespace: test-ns
  name: java-web-app-pod
  labels:
    app: java-web-app
spec:
  containers:
  - name: java-web-app-container
    image: dockersampath/webpage:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: java-web-app-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: java-web-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
